# Generated by Django 3.1.3 on 2021-04-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_Grafana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('temperatura_inicio', models.IntegerField(default=0)),
                ('temperatura_historico', models.IntegerField(default=0)),
                ('temperatura_variable', models.CharField(max_length=200)),
                ('presion_inicio', models.IntegerField(default=0)),
                ('presion_historico', models.IntegerField(default=0)),
                ('presion_variable', models.CharField(max_length=200)),
                ('humedad_inicio', models.IntegerField(default=0)),
                ('humedad_historico', models.IntegerField(default=0)),
                ('humedad_variable', models.CharField(max_length=200)),
            ],
        ),
    ]
