# Generated by Django 3.1.3 on 2021-04-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion_grafana',
            old_name='humedad_variable',
            new_name='buckets_variable',
        ),
        migrations.RenameField(
            model_name='configuracion_grafana',
            old_name='presion_variable',
            new_name='cultivos_variable',
        ),
        migrations.RenameField(
            model_name='configuracion_grafana',
            old_name='temperatura_variable',
            new_name='finca_variable',
        ),
    ]
