# Generated by Django 3.1.3 on 2021-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210414_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_grafana',
            name='uv_historico',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracion_grafana',
            name='uv_inicio',
            field=models.IntegerField(default=0),
        ),
    ]
