# Generated by Django 3.1.3 on 2021-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20210417_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_grafana',
            name='comparacion',
            field=models.IntegerField(default=0),
        ),
    ]
