# Generated by Django 3.1.3 on 2021-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_configuracion_grafana_comparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_grafana',
            name='medidas_variable',
            field=models.CharField(default='holi', max_length=200),
            preserve_default=False,
        ),
    ]
