# Generated by Django 3.1.3 on 2021-04-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_configuracion_grafana_finca2_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion_grafana',
            name='complement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='configuracion_grafana',
            name='render',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
